/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SendMaillSSL;
import Model.Account;
import Model.AccountDAO;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Monkey.TNT
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    private String codeforgot;

    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Email = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfemail = new javax.swing.JTextField();
        btnNewPass = new javax.swing.JButton();
        Code = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCodeConfirm = new javax.swing.JTextField();
        btnCodeemail = new javax.swing.JButton();
        NewPassword = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfPassNew = new javax.swing.JPasswordField();
        txtfConPassNew = new javax.swing.JPasswordField();
        btnResetPassword = new javax.swing.JButton();
        lbWarning = new javax.swing.JLabel();

        setTitle("ForgotPassword");
        getContentPane().setLayout(new java.awt.CardLayout());

        Email.setBackground(new java.awt.Color(42, 142, 191));
        Email.setPreferredSize(new java.awt.Dimension(359, 133));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");

        txtfemail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtfemail.setForeground(new java.awt.Color(102, 102, 102));
        txtfemail.setBorder(null);

        btnNewPass.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnNewPass.setForeground(new java.awt.Color(42, 142, 191));
        btnNewPass.setText("Get New Password");
        btnNewPass.setBorder(null);
        btnNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmailLayout = new javax.swing.GroupLayout(Email);
        Email.setLayout(EmailLayout);
        EmailLayout.setHorizontalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        EmailLayout.setVerticalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(Email, "ForgotEmail");

        Code.setBackground(new java.awt.Color(42, 142, 191));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(42, 142, 191));
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Please enter the confirmation code that was texted to your email");
        jTextField3.setBorder(null);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Code");

        tfCodeConfirm.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfCodeConfirm.setForeground(new java.awt.Color(102, 102, 102));

        btnCodeemail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCodeemail.setForeground(new java.awt.Color(42, 142, 191));
        btnCodeemail.setText("Confirm");
        btnCodeemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CodeLayout = new javax.swing.GroupLayout(Code);
        Code.setLayout(CodeLayout);
        CodeLayout.setHorizontalGroup(
            CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CodeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCodeemail))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CodeLayout.setVerticalGroup(
            CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCodeemail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(Code, "ForgotCode");

        NewPassword.setBackground(new java.awt.Color(42, 142, 191));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm New Password");

        txtfPassNew.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtfPassNew.setForeground(new java.awt.Color(102, 102, 102));
        txtfPassNew.setBorder(null);
        txtfPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfPassNewKeyReleased(evt);
            }
        });

        txtfConPassNew.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtfConPassNew.setForeground(new java.awt.Color(102, 102, 102));
        txtfConPassNew.setBorder(null);

        btnResetPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(42, 142, 191));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        lbWarning.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout NewPasswordLayout = new javax.swing.GroupLayout(NewPassword);
        NewPassword.setLayout(NewPasswordLayout);
        NewPasswordLayout.setHorizontalGroup(
            NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPasswordLayout.createSequentialGroup()
                .addGroup(NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPasswordLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(218, 218, 218))
                            .addGroup(NewPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(NewPasswordLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfConPassNew)
                            .addComponent(txtfPassNew)
                            .addGroup(NewPasswordLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(111, 111, 111)))))
                .addGap(39, 39, 39))
        );
        NewPasswordLayout.setVerticalGroup(
            NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPasswordLayout.createSequentialGroup()
                .addGroup(NewPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfPassNew, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfConPassNew, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(NewPassword, "ForgotNewPass");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCodeemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeemailActionPerformed
        if (tfCodeConfirm.getText().equals(codeforgot)) {
            showPanelForgot("ForgotNewPass");
        } else {
            JOptionPane.showMessageDialog(null, "Code the wrong");
        }

    }//GEN-LAST:event_btnCodeemailActionPerformed

    private void btnNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPassActionPerformed
        if (txtfemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email is empty");
        } else {

            try {
                AccountDAO accountDAO = new AccountDAO();
                Account account;
                account = accountDAO.checkmailaccount(txtfemail.getText());
                if (account == null) {
                    JOptionPane.showMessageDialog(null, "Email does not exist");
                } else {
                    Login login = new Login();
                    SendMaillSSL sendforgot = new SendMaillSSL();
                    codeforgot = login.codeRandom();
                    sendforgot.SendMail(txtfemail.getText(), codeforgot);
                    showPanelForgot("ForgotCode");

                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnNewPassActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed

        if (String.valueOf(txtfPassNew.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password is empty");
        } else if (String.valueOf(txtfConPassNew.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirm password is empty");
        } else if (String.valueOf(txtfPassNew.getPassword()) != String.valueOf(txtfConPassNew.getPassword())) {
            if (String.valueOf(txtfPassNew.getPassword()).equals(String.valueOf(txtfConPassNew.getPassword()))) {
                try {
                    AccountDAO accountDAO = new AccountDAO();
                    Account account = new Account();
                    account = accountDAO.thesamepass(String.valueOf(txtfPassNew.getPassword()));
                    if (account != null) {
                        JOptionPane.showMessageDialog(null, "Use a different password");
                    } else {
                        accountDAO.updatepassword(txtfemail.getText(), String.valueOf(txtfPassNew.getPassword()));
                        JOptionPane.showMessageDialog(null, "Reset Password Success");
                        this.setVisible(false);
                    }

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Confirm password the wrong");
            }

        }


    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void txtfPassNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPassNewKeyReleased
        try {
            AccountDAO accountDAO = new AccountDAO();
            Account account = new Account();
            account = accountDAO.thesamepass(String.valueOf(txtfPassNew.getPassword()));
            if (account != null) {
                lbWarning.setText("New Password should not be same as old password");
            } else {
                lbWarning.setText(null);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtfPassNewKeyReleased

    public void showPanelForgot(String panelName) {
        CardLayout layoutpanel = (CardLayout) getContentPane().getLayout();
        layoutpanel.show(getContentPane(), panelName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Code;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel NewPassword;
    private javax.swing.JButton btnCodeemail;
    private javax.swing.JButton btnNewPass;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JTextField tfCodeConfirm;
    private javax.swing.JPasswordField txtfConPassNew;
    private javax.swing.JPasswordField txtfPassNew;
    private javax.swing.JTextField txtfemail;
    // End of variables declaration//GEN-END:variables
}
