
import com.sun.rowset.CachedRowSetImpl;
import com.sun.rowset.JdbcRowSetImpl;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.RowSet;
import javax.sql.RowSetEvent;
import javax.sql.RowSetListener;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Monkey.TNT
 */
public class Session1 extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    RowSet rowSet = null;  //co nhung chuc nang cua ResultSet
    
    public void SetupSQL() {
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=Demojdbc";
            con = DriverManager.getConnection(url, "sa", "230697");
            System.out.println("Connect success");
            
            String sql = "select * from Student";
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            rs = stmt.executeQuery(sql);
            rowSet = new JdbcRowSetImpl(rs);
            
            rowSet.addRowSetListener(new RowSetListener() {
                @Override
                public void rowSetChanged(RowSetEvent event) {
                    System.out.println("row set changed");
                }
                
                @Override
                public void rowChanged(RowSetEvent event) {
                    System.out.println("row changed");
                }
                
                @Override
                public void cursorMoved(RowSetEvent event) {
                    System.out.println("Curor moved");
                }
            });
            
            DatabaseMetaData dbmdt = con.getMetaData();
            System.out.println("SSE " + dbmdt.getSearchStringEscape());
            System.out.println("Driver Name " + dbmdt.getDriverName());
            
            ResultSetMetaData rsmd = rs.getMetaData();
            System.out.println(rsmd.getColumnCount());
            for (int i = 0; i < 4; i++) {
                System.out.println(rsmd.getColumnName(i + 1));
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public Session1() {
        initComponents();
        SetupSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        txtfAge = new javax.swing.JTextField();
        txtfAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtfRow = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        btnTransacsion = new javax.swing.JButton();
        btnCached = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Address");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAddStudent.setText("AddStudent");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnTransacsion.setText("Transacsion");
        btnTransacsion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransacsionActionPerformed(evt);
            }
        });

        btnCached.setText("Create cached rowset");
        btnCached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCachedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addComponent(btnFirst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtfName)
                                    .addComponent(txtfAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFind)
                                    .addComponent(btnAdd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrevious)
                                .addGap(29, 29, 29)
                                .addComponent(btnCached)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtfRow, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransacsion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext)
                            .addComponent(btnPrevious)
                            .addComponent(btnFirst))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo)
                            .addComponent(btnLast))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCached)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddStudent)
                            .addComponent(btnTransacsion))
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            if (rs.next()) {
                displayToForm();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void displayToForm() throws SQLException {
        String name = rs.getString("name");
        int age = rs.getInt("age");
        String address = rs.getString("address");
        txtfName.setText(name);
        txtfAddress.setText(address);
        txtfAge.setText(age + "");
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String name = txtfName.getText();
            int age = Integer.parseInt(txtfAge.getText());
            String address = txtfAddress.getText();
//            String sql = "insert into Student values('" + name + "','" + address + "'," + age + ")";
//            int result = stmt.executeUpdate(sql);
//            System.out.println("Inserted" + result);
//            if (result != 0) {
//                JOptionPane.showMessageDialog(rootPane, "added");
//            }
//            rs = stmt.executeQuery("select * from Student");

//Move to insert row
            rs.moveToInsertRow();
            rs.updateString("name", name);
            rs.updateString("address", address);
            rs.updateInt("age", age);
            rs.insertRow();
            JOptionPane.showMessageDialog(rootPane, "Inserted");
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
//            String sql = "update Student set name=? , age=?, address=? where id=? ";
//            PreparedStatement psmt = con.prepareStatement(sql);
//            psmt.setString(1, txtfName.getText());
//            psmt.setString(3, txtfAddress.getText());
//            psmt.setInt(2, Integer.parseInt(txtfAge.getText()));
//            psmt.setInt(4, rs.getInt("id"));
//            psmt.executeUpdate();

            rs.updateString(2, txtfName.getText());
            rs.updateString(3, txtfAddress.getText());
            rs.updateInt(4, Integer.parseInt(txtfAge.getText()));
            rs.updateRow();
            
            System.out.println("Updated");
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            CallableStatement cstm = con.prepareCall("{call FindStd(?)}");
            String namelike = "%" + txtfName.getText() + "%";
            cstm.setString(1, namelike);
            rs = cstm.executeQuery();
            if (rs.next()) {
                String name = rs.getString("name");
                int age = rs.getInt("age");
                String address = rs.getString("address");
                txtfName.setText(name);
                txtfAddress.setText(address);
                txtfAge.setText(age + "");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        try {
            if (rs.previous()) {
                displayToForm();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        try {
            if (rs.absolute(Integer.parseInt(txtfRow.getText()))) {
                displayToForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cannot go to that row");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnGoActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            if (rs.first()) {
                displayToForm();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            if (rs.last()) {
                displayToForm();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (rs.getRow() != 0) {
                rs.deleteRow();
                JOptionPane.showMessageDialog(rootPane, "Deleted");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        try {
            con.setAutoCommit(false);
            stmt = con.createStatement();
            String sql1 = "insert into Student values('Mr.D','VL',14)";
            String sql2 = "insert into Student values('Mr.E','VFL',24)";
            stmt.addBatch(sql1);
            stmt.addBatch(sql2);
            stmt.executeBatch();
            con.setAutoCommit(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnTransacsionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacsionActionPerformed
        Savepoint sp = null;
        try {
            con.setAutoCommit(false);
            sp = con.setSavepoint("BeforeInsert");
            String sql1 = "insert into Student values('Mr.F','DSD',23)";
            String sql2 = "insert into Student values('Mr.G','GFC',17)";
            stmt.executeUpdate(sql1);
            stmt.executeUpdate(sql2);
            con.commit();
            con.setAutoCommit(true);
        } catch (SQLException ex) {
            try {
                con.rollback(sp);
                con.setAutoCommit(true);
            } catch (SQLException ex1) {
                Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        

    }//GEN-LAST:event_btnTransacsionActionPerformed

    private void btnCachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCachedActionPerformed
        try {
            CachedRowSet crs = new CachedRowSetImpl();
            crs.populate(rs);
            con.close();
            crs.absolute(3);
            crs.deleteRow();
            String url = "jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=Demojdbc";
            Connection newcon = DriverManager.getConnection(url, "sa", "230697");
            crs.acceptChanges(newcon);
        } catch (SQLException ex) {
            Logger.getLogger(Session1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCachedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Session1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnCached;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnTransacsion;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtfAddress;
    private javax.swing.JTextField txtfAge;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtfRow;
    // End of variables declaration//GEN-END:variables
}
