/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameJPanel;

import javax.swing.JPanel;

/**
 *
 * @author Monkey.TNT
 */
public class MainWindow extends javax.swing.JFrame {

    private JPanel childJPanel;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPanel1 = new javax.swing.JButton();
        btnPanel2 = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        mnTopMenu = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnPanel1 = new javax.swing.JMenuItem();
        mnPanel2 = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnPanel1.setText("Panel1");
        btnPanel1.setFocusable(false);
        btnPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPanel1);

        btnPanel2.setText("Panel2");
        btnPanel2.setFocusable(false);
        btnPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPanel2);

        pnMain.setLayout(new java.awt.BorderLayout());

        mnFile.setText("File");

        mnPanel1.setText("ShowPanel1");
        mnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPanel1ActionPerformed(evt);
            }
        });
        mnFile.add(mnPanel1);

        mnPanel2.setText("ShowPanel2");
        mnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPanel2ActionPerformed(evt);
            }
        });
        mnFile.add(mnPanel2);

        mnExit.setText("Exit");
        mnFile.add(mnExit);

        mnTopMenu.add(mnFile);

        mnEdit.setText("Edit");
        mnTopMenu.add(mnEdit);

        setJMenuBar(mnTopMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
        showPanel(new Panel1());
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel2ActionPerformed
        showPanel(new Panel2());
    }//GEN-LAST:event_btnPanel2ActionPerformed

    private void mnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPanel1ActionPerformed
        showPanel(new Panel1());
    }//GEN-LAST:event_mnPanel1ActionPerformed

    private void mnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPanel2ActionPerformed
        showPanel(new Panel2());
    }//GEN-LAST:event_mnPanel2ActionPerformed

    private void showPanel(JPanel panel) {
        childJPanel = panel;
        pnMain.removeAll();
        pnMain.add(childJPanel);
        pnMain.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnPanel1;
    private javax.swing.JMenuItem mnPanel2;
    private javax.swing.JMenuBar mnTopMenu;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
