/* FileName:       AddEmployee.java
* Purpose:         This Class is used to Add a new Employee record on DB. 
* Features covered : JDBC Transactions
* Author:           Vincent
 * Created Date:    18-Nov-2013
* Version:         1.1 (Initial Version)
* Last Modified:   05-Dec-2013*/
package com.sample.home;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class AddEmployee extends javax.swing.JFrame {
   
    private boolean idGenerated;
    private boolean isVerified;
    private boolean isPersonalEdited;
    private boolean isEducationEdited;
    private final String[] departments = {"Software","Finance","HR","Admin","Vendor"};
    private int mEmp_ID;
     //DB transaction parameters
    private Connection contransaction;
    private Statement statement;
    private Savepoint savepointEducation;
    
    
    /**
     * Creates new form NewJFrame1
     */
    public AddEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
        mDept.removeAllItems();
        //Populate combo box
        for(int i=0;i<departments.length;i++)
        {
                mDept.addItem(departments[i]);
        }
        makeEditableEducationFields(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAddEmployee = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        mName = new java.awt.TextField();
        mEmail = new java.awt.TextField();
        btnGenerateId = new javax.swing.JButton();
        mDept = new javax.swing.JComboBox();
        btnEditPersonal = new javax.swing.JButton();
        panelEducation = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        mDegree = new java.awt.TextField();
        mCollege = new java.awt.TextField();
        mAggregate = new java.awt.TextField();
        btnVerify = new javax.swing.JButton();
        btnEditEducation = new javax.swing.JButton();
        label8 = new java.awt.Label();
        mEmpId = new java.awt.TextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 570));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 56));

        lblAddEmployee.setAlignment(java.awt.Label.CENTER);
        lblAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddEmployee.setText("Add Employee Detail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal"));

        label2.setText("Name");

        label3.setText("Email");

        label4.setText("Department");

        mName.setPreferredSize(new java.awt.Dimension(8, 20));

        btnGenerateId.setText("GenerateEmpID");
        btnGenerateId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateIdActionPerformed(evt);
            }
        });

        mDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditPersonal.setText("Edit");
        btnEditPersonal.setEnabled(false);
        btnEditPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mDept, 0, 172, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditPersonal)
                .addGap(18, 18, 18)
                .addComponent(btnGenerateId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerateId)
                        .addComponent(mDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditPersonal)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelEducation.setBorder(javax.swing.BorderFactory.createTitledBorder("Education"));

        label5.setText("Degree");

        label6.setText("College");

        label7.setText("Aggregate");

        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        btnEditEducation.setText("Edit");
        btnEditEducation.setEnabled(false);
        btnEditEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEducationActionPerformed(evt);
            }
        });

        label8.setText("Emp_ID");

        mEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmpIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEducationLayout = new javax.swing.GroupLayout(panelEducation);
        panelEducation.setLayout(panelEducationLayout);
        panelEducationLayout.setHorizontalGroup(
            panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEducationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEducationLayout.createSequentialGroup()
                        .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mAggregate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEducationLayout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEmpId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelEducationLayout.createSequentialGroup()
                                .addComponent(btnEditEducation)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelEducationLayout.setVerticalGroup(
            panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEducationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mDegree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCollege, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEducationLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEducationLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnVerify)
                                .addComponent(btnEditEducation))
                            .addComponent(mAggregate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelEducation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
         try {
                btnVerifyPerformed(evt);
        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnGenerateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateIdActionPerformed
        // TODO add your handling code here:
         try {
                btnGenerateIDPerformed(evt);
        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
    }//GEN-LAST:event_btnGenerateIdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         try {
                btnCancelPerformed(evt);
        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
                btnSavePerformed(evt);
        } catch (SQLException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }	
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPersonalActionPerformed
        // TODO add your handling code here:
         try {
              btnEditPersonalPerformed(evt);
               
        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
    }//GEN-LAST:event_btnEditPersonalActionPerformed

    private void btnEditEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEducationActionPerformed
        // TODO add your handling code here:
        try {
              btnEditEducationPerformed(evt);
        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
    }//GEN-LAST:event_btnEditEducationActionPerformed

    private void mEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEmpIdActionPerformed

    //SQLSERVER CONNECTION
    private Connection getSQLServerConnection()throws Exception
    {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").newInstance();
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=employee;","sa","exemplarr@123$");
            return con;

    }
    private void btnGenerateIDPerformed(ActionEvent event)
    {
        try
        {
            if((mName.getText().toString().equals("")) && mEmail.getText().toString().equals("")){
                        // Display an error message.
                String message = "Please Enter Name and Email!";
                String title = "Error";
                JOptionPane.showMessageDialog(null,message,title,JOptionPane.ERROR_MESSAGE);
            }else{
                contransaction = getSQLServerConnection();
                contransaction.setAutoCommit(false);
                mEmp_ID = generateMaxID()+1;
                statement = contransaction.createStatement();
                int result = insertDetailsToTable("personal");
                if(result>0){
                    idGenerated = true;
                    makeEditableEducationFields(true);
                    mEmpId.setText(mEmp_ID+"");
                    btnGenerateId.setEnabled(false);
                    makeEditablePersonalFields(false);
                    
                }
             }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    //edit personal details
    private void btnEditPersonalPerformed(ActionEvent event)
    {
       if(idGenerated)
       {
           try
           {
               //Rollback totally
               contransaction.rollback();
               makeEditablePersonalFields(true);
               isPersonalEdited = true;
           }
           catch(Exception e)
           {
               e.printStackTrace();
           }
       }
    }
    //edit education details
    private void btnEditEducationPerformed(ActionEvent event)
    {
            try
            {
               //check whether the savepoint is available 
               if(!isPersonalEdited)
               {
                   contransaction.rollback(savepointEducation);
               }
               makeEditableEducationFields(true);
               isEducationEdited = true;
               
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
    }
    // verify employee details
    private void btnVerifyPerformed(ActionEvent event)throws Exception
    {
        if(idGenerated)
        {
            if(!(mName.getText().toString().equals("")) && !(mEmail.getText().toString().equals(""))
                                && !(mDegree.getText().toString().equals("")) && !(mCollege.getText().toString().equals("")) &&
                                        !(mAggregate.getText().toString().equals(""))){
                            if(contransaction!=null)
                            {
                                    JOptionPane.showMessageDialog(null,"Verify employee details and click Save.",
                                            "Verification",JOptionPane.DEFAULT_OPTION);
                                    lblAddEmployee.setBounds(5, 11, 300, 23);
                                    lblAddEmployee.setText("ADD NEW EMPLOYEE - VERIFICATION");
                                    savepointEducation = contransaction.setSavepoint("sp_education");
                                    int result = insertDetailsToTable("education");
                                    if(result>0)
                                    {
                                            isVerified=true;
                                            btnEditEducation.setEnabled(true);
                                            btnEditPersonal.setEnabled(true);
                                            btnGenerateId.setEnabled(false);
                                            btnVerify.setEnabled(false);
                                            makeEditableEducationFields(false);
                                            makeEditablePersonalFields(false);
                                            btnSave.setEnabled(true);
                                    }
                            }

            }
            else
            {
                String message = "Please Enter values for blank fields before verification";
                String title = "Error";
                JOptionPane.showMessageDialog(null,message,title,JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnCancelPerformed(ActionEvent event) throws SQLException
    {
            if(idGenerated || isVerified){
                    contransaction.rollback();
            }
            this.setVisible(false);
            new EmployeeDetails().setVisible(true);
    }

    private void btnSavePerformed(ActionEvent event) throws SQLException
    {
         if(contransaction!=null)
         {
             if(isVerified)
             {
                if(isPersonalEdited)
                {	//personal and education details has been rollback, so insert again.
                        insertDetailsToTable("personal");
                        insertDetailsToTable("education");
                }else if(isEducationEdited)
                {
                        //education details has been rollback, so insert again.
                        insertDetailsToTable("education");
                }
                contransaction.commit();
                JOptionPane.showMessageDialog(null,"Employee ' "+mName.getText().toString()+" '  record added successfully","Status",JOptionPane.DEFAULT_OPTION);
                idGenerated=false;
                isVerified=false;
                isEducationEdited=false;
                isPersonalEdited=false;
                this.setVisible(false);
                new EmployeeDetails().setVisible(true);
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"Verify details first.","Confirmation",JOptionPane.DEFAULT_OPTION);
             }
         }
    }
    
    private int generateMaxID()
    {
        try{
            Connection con = getSQLServerConnection();
            Statement statement = con.createStatement();
            String query = "select MAX(emp_ID) from tbl_emp_personal";
            ResultSet rs = statement.executeQuery(query);
            rs.next();
            int maxID = rs.getInt(1);
            con.close();
            return maxID;
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return 0;
        
    }
    
    private void makeEditablePersonalFields(boolean flag)
    {
              mName.setEnabled(flag);
              mEmail.setEnabled(flag);
              mDept.setEnabled(flag);
    }
    private void makeEditableEducationFields(boolean flag)
    {
              mDegree.setEnabled(flag);
              mCollege.setEnabled(flag);
              mAggregate.setEnabled(flag);
    }
    
    private int insertDetailsToTable(String category)throws SQLException
    {
        int result = 0;
        String insertTableSQL = "";
        if(category.equals("personal"))
        {
            insertTableSQL = "INSERT INTO tbl_emp_personal"
                                    + "(emp_ID,name,email,department)" + "VALUES"
                                    + "("+mEmp_ID+", '"+mName.getText().toString()+"','"+mEmail.getText().toString()+"','"
                                    + mDept.getSelectedItem().toString() + "')";
                  result = statement.executeUpdate(insertTableSQL);
        }
        else if(category.equals("education"))
        {
            insertTableSQL = "INSERT INTO tbl_emp_education"
                                    + "(emp_ID,degree,college,aggregate)" + "VALUES"
                                    + "("+mEmpId.getText().toString()+",'"+mDegree.getText().toString()+"','"+mCollege.getText().toString()+"','"
                                    + mAggregate.getText().toString() + "')";
                    result = statement.executeUpdate(insertTableSQL);
        }
        return result;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEditEducation;
    private javax.swing.JButton btnEditPersonal;
    private javax.swing.JButton btnGenerateId;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVerify;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label lblAddEmployee;
    private java.awt.TextField mAggregate;
    private java.awt.TextField mCollege;
    private java.awt.TextField mDegree;
    private javax.swing.JComboBox mDept;
    private java.awt.TextField mEmail;
    private java.awt.TextField mEmpId;
    private java.awt.TextField mName;
    private javax.swing.JPanel panelEducation;
    // End of variables declaration//GEN-END:variables
}
