
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MacOS
 */
public final class AddInJTable extends javax.swing.JFrame {
    
    private Connection con;
    private PreparedStatement stmt;
    private ResultSet rs;
    private ResultSetMetaData rsmd;
    private Statement stm;
    private DefaultTableModel dtm;
    
    public AddInJTable() throws ClassNotFoundException {
        initComponents();
        try {
            getConnection();
        } catch (Exception e) {
            e.getMessage();
        }
        Displaytable();
    }
    
    private Connection getConnection() throws ClassNotFoundException, SQLException {
        String URL = "jdbc:sqlserver://localhost:1433;databaseName=Project";
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con = DriverManager.getConnection(URL, "sa", "230697");
        return con;
    }
    
    public void Displaytable() throws ClassNotFoundException {
        try {
            
            String sql = "select * from tblUser";
            stm = getConnection().createStatement();
            rs = stm.executeQuery(sql);
            rsmd = rs.getMetaData();
            int columns = rsmd.getColumnCount();
            dtm = new DefaultTableModel();
            Vector columns_name = new Vector();
            Vector data_row = new Vector();
            TableColumn columnsa=null;
            for (int i = 1; i <= columns; i++) {
                columns_name.addElement(rsmd.getColumnName(i));
                columnsa = AddInJTable.getColumnModel().getColumn(i);
                if (i == columns) {
                    columnsa.setPreferredWidth(20);
                   
                    columns_name.addElement("Delete");
                }
                
            }
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()) {
                
                data_row = new Vector();
                for (int j = 1; j <= columns; j++) {
                    data_row.addElement(rs.getString(j));
                    if (j == columns) {
                        data_row.add("");
                    }
                }
                dtm.addRow(data_row);
                
            }
            
            AddInJTable.setModel(dtm);
            
            
            Action deletea = new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    AddInJTable = (JTable) e.getSource();
                    int modelRow = Integer.valueOf(e.getActionCommand());
                    ((DefaultTableModel) AddInJTable.getModel()).removeRow(modelRow);
                    
                }
            };
            
            //JLabel lbdelete = new JLabel(new ImageIcon("image/Exit.png"));
         ButtonColumn bc = new ButtonColumn(AddInJTable, deletea, 3);            
         //   bc.setMnemonic(KeyEvent.VK_D);
        } catch (SQLException ex) {
            ex.getMessage();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        AddInJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddInJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(AddInJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddInJTable().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddInJTable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AddInJTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
