/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import BackgroundColor.SetBackgroundbtn;
import Controller.Valid;
import Model.DataHelper;
import Model.MyDAO;
import Model.tblDocument;
import Model.tblDocumentDAO;
import Model.tblDocumentModel;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author MacOS
 */
public class DBookLib extends javax.swing.JDialog {

    MyDAO bookDAO = new tblDocumentDAO();
    public int number;
    static Point comPoint = null;
    //Add cbb
    private Connection conn;
    private PreparedStatement stmt;
    private ResultSet rs;
    private JTable TableBookLib;
    DefaultComboBoxModel cbbCateModel = new DefaultComboBoxModel();
    DefaultComboBoxModel cbbPubModel = new DefaultComboBoxModel();

    public DBookLib(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public DBookLib(String id, String name, String description, String cateid, String pulisherid, String quantity, String price, String year, String edition, String author, int number, JTable tablebooklib, java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdBook.setText(id);
        txtNameBook.setText(name);
        txtDescription.setText(description);

        txtQuantityBook.setText(quantity);
        txtPriceBook.setText(price);
        txtYearBook.setText(year);
        txtNTimesBook.setText(edition);
        txtAuthorBook.setText(author);
        this.number = number;
        this.TableBookLib = tablebooklib;
        try {
            conn = DataHelper.getConnection();
        } catch (Exception e) {
            e.getMessage();
        }
        AddTlCbb();
        AddNXBCbb();
        if (number == 1) {
            txtIdBook.setEditable(false);
            txtNameBook.requestFocus();
            cbbIdCate.setSelectedItem(cateid);
            cbbIdPulisher.setSelectedItem(pulisherid);
        }
    }

    public void showTableBook(JTable tablebooklib) {
        tblDocumentModel documentModel = new tblDocumentModel();
        documentModel.setData(new tblDocumentDAO().GetAll());
        tablebooklib.setModel(documentModel);
    }

    private void AddTlCbb() {
        cbbCateModel.addElement("");
        try {
            String sql = "select * from tblCategory";
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                cbbCateModel.addElement(rs.getString("CategoryId"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void AddNXBCbb() {
        cbbPubModel.addElement("");
        try {
            String sql = "select * from tblPublisher";
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                cbbPubModel.addElement(rs.getString("PublisherId"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palD = new javax.swing.JPanel();
        btnX = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        txtIdBook = new javax.swing.JTextField();
        Sepa1 = new javax.swing.JSeparator();
        lb2 = new javax.swing.JLabel();
        txtNameBook = new javax.swing.JTextField();
        Sepa2 = new javax.swing.JSeparator();
        txtAuthorBook = new javax.swing.JTextField();
        Sepa3 = new javax.swing.JSeparator();
        lb4 = new javax.swing.JLabel();
        txtPriceBook = new javax.swing.JTextField();
        lb5 = new javax.swing.JLabel();
        Sepa4 = new javax.swing.JSeparator();
        lb11 = new javax.swing.JLabel();
        txtYearBook = new javax.swing.JTextField();
        Sepa5 = new javax.swing.JSeparator();
        lb6 = new javax.swing.JLabel();
        txtNTimesBook = new javax.swing.JTextField();
        Sepa6 = new javax.swing.JSeparator();
        lb7 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        cbbIdPulisher = new javax.swing.JComboBox<>();
        cbbIdCate = new javax.swing.JComboBox<>();
        ScrollPa2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lb13 = new javax.swing.JLabel();
        btnSave = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        txtQuantityBook = new javax.swing.JTextField();
        Sepa8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        palD.setBackground(new java.awt.Color(98, 98, 110));
        palD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                palDMouseDragged(evt);
            }
        });
        palD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                palDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                palDMouseReleased(evt);
            }
        });

        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("Mã Sách");

        txtIdBook.setBackground(new java.awt.Color(98, 98, 110));
        txtIdBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIdBook.setForeground(new java.awt.Color(255, 255, 255));
        txtIdBook.setBorder(null);
        txtIdBook.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdBook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdBookFocusLost(evt);
            }
        });

        lb2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("Tên Sách");

        txtNameBook.setBackground(new java.awt.Color(98, 98, 110));
        txtNameBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNameBook.setForeground(new java.awt.Color(255, 255, 255));
        txtNameBook.setBorder(null);
        txtNameBook.setCaretColor(new java.awt.Color(255, 255, 255));

        txtAuthorBook.setBackground(new java.awt.Color(98, 98, 110));
        txtAuthorBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAuthorBook.setForeground(new java.awt.Color(255, 255, 255));
        txtAuthorBook.setBorder(null);
        txtAuthorBook.setCaretColor(new java.awt.Color(255, 255, 255));

        lb4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("Tác Giả");

        txtPriceBook.setBackground(new java.awt.Color(98, 98, 110));
        txtPriceBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPriceBook.setForeground(new java.awt.Color(255, 255, 255));
        txtPriceBook.setBorder(null);
        txtPriceBook.setCaretColor(new java.awt.Color(255, 255, 255));

        lb5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("Đơn Giá");

        lb11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb11.setForeground(new java.awt.Color(255, 255, 255));
        lb11.setText("Mã Nhà Xuất Bản");

        txtYearBook.setBackground(new java.awt.Color(98, 98, 110));
        txtYearBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtYearBook.setForeground(new java.awt.Color(255, 255, 255));
        txtYearBook.setBorder(null);
        txtYearBook.setCaretColor(new java.awt.Color(255, 255, 255));

        lb6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("Năm Xuất Bản");

        txtNTimesBook.setBackground(new java.awt.Color(98, 98, 110));
        txtNTimesBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNTimesBook.setForeground(new java.awt.Color(255, 255, 255));
        txtNTimesBook.setBorder(null);
        txtNTimesBook.setCaretColor(new java.awt.Color(255, 255, 255));

        lb7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb7.setForeground(new java.awt.Color(255, 255, 255));
        lb7.setText("Lần Xuất Bản");

        lb9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb9.setForeground(new java.awt.Color(255, 255, 255));
        lb9.setText("Số Lượng");

        lb12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb12.setForeground(new java.awt.Color(255, 255, 255));
        lb12.setText("Mã Thể Loại");

        cbbIdPulisher.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbIdPulisher.setModel(cbbPubModel);
        cbbIdPulisher.setBorder(null);

        cbbIdCate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbIdCate.setModel(cbbCateModel);
        cbbIdCate.setBorder(null);

        txtDescription.setBackground(new java.awt.Color(98, 98, 110));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setCaretColor(new java.awt.Color(255, 255, 255));
        ScrollPa2.setViewportView(txtDescription);

        lb13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb13.setForeground(new java.awt.Color(255, 255, 255));
        lb13.setText("Tóm Tắt Nội Dung Sách");

        btnSave.setBackground(new java.awt.Color(126, 130, 139));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        lb3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("Lưu");

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtQuantityBook.setBackground(new java.awt.Color(98, 98, 110));
        txtQuantityBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQuantityBook.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantityBook.setBorder(null);
        txtQuantityBook.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout palDLayout = new javax.swing.GroupLayout(palD);
        palD.setLayout(palDLayout);
        palDLayout.setHorizontalGroup(
            palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(palDLayout.createSequentialGroup()
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sepa1)
                                .addComponent(lb1)
                                .addComponent(txtIdBook, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sepa2)
                                .addComponent(lb2)
                                .addComponent(txtNameBook, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(lb5)
                            .addComponent(lb12)
                            .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sepa3)
                                .addComponent(lb4)
                                .addComponent(txtAuthorBook, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(cbbIdCate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sepa4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtPriceBook)))
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(palDLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtYearBook, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(Sepa5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNTimesBook, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Sepa6, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palDLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnX, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palDLayout.createSequentialGroup()
                                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(palDLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(lb9)
                                                .addGap(18, 18, 18)
                                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Sepa8)
                                                    .addComponent(txtQuantityBook, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(ScrollPa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb13))
                                        .addContainerGap())))))
                    .addGroup(palDLayout.createSequentialGroup()
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbIdPulisher, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        palDLayout.setVerticalGroup(
            palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palDLayout.createSequentialGroup()
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnX)
                    .addGroup(palDLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Sepa5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNTimesBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Sepa6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(palDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(palDLayout.createSequentialGroup()
                                .addComponent(lb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAuthorBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb5)
                                .addGap(7, 7, 7)
                                .addComponent(txtPriceBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(lb12)
                                .addGap(24, 24, 24)
                                .addComponent(cbbIdCate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palDLayout.createSequentialGroup()
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb9)
                                    .addGroup(palDLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtQuantityBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(Sepa8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ScrollPa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbIdPulisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        this.dispose();
        showTableBook(TableBookLib);
    }//GEN-LAST:event_btnXMouseClicked

    private void palDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMousePressed
        comPoint = evt.getPoint();
    }//GEN-LAST:event_palDMousePressed

    private void palDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMouseReleased
        comPoint = null;
    }//GEN-LAST:event_palDMouseReleased

    private void palDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMouseDragged
        Point cPoint = evt.getLocationOnScreen();
        this.setLocation(cPoint.x - comPoint.x, cPoint.y - comPoint.y);
    }//GEN-LAST:event_palDMouseDragged

    private void btnSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseReleased
        new SetBackgroundbtn(btnSave).mouseReleased(evt);
    }//GEN-LAST:event_btnSaveMouseReleased

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        new SetBackgroundbtn(btnSave).mousePressed(evt);
    }//GEN-LAST:event_btnSaveMousePressed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if (number == 1) {
            if (txtIdBook.getText().length() != 0
                    && txtNameBook.getText().length() != 0
                    && txtDescription.getText().length() != 0
                    && String.valueOf(cbbIdCate.getSelectedItem()).length() != 0
                    && String.valueOf(cbbIdPulisher.getSelectedItem()).length() != 0
                    && txtQuantityBook.getText().length() != 0
                    && txtPriceBook.getText().length() != 0
                    && txtYearBook.getText().length() != 0
                    && txtNTimesBook.getText().length() != 0
                    && txtAuthorBook.getText().length() != 0) {
                if (Valid.ValidN(txtPriceBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtPriceBook.requestFocus();
                } else if (Valid.ValidYear(txtYearBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtYearBook.requestFocus();
                } else if (Valid.ValidN(txtNTimesBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtNTimesBook.requestFocus();
                } else if (Valid.ValidN(txtQuantityBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtQuantityBook.requestFocus();
                } else if (bookDAO.Update(new tblDocument(txtIdBook.getText(), txtNameBook.getText(), txtDescription.getText(), String.valueOf(cbbIdCate.getSelectedItem()), cbbIdPulisher.getSelectedItem().toString(),
                        Integer.parseInt(txtQuantityBook.getText()), txtPriceBook.getText(), txtYearBook.getText(),
                        Integer.parseInt(txtNTimesBook.getText()), txtAuthorBook.getText())) != null) {
                    JOptionPane.showMessageDialog(null, "Sửa tài liệu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    showTableBook(TableBookLib);
                    this.dispose();

                }

            } else {
                JOptionPane.showMessageDialog(null, "Sửa tài liệu thất bại bạn không được để trống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            if (txtIdBook.getText().length() != 0
                    && txtNameBook.getText().length() != 0
                    && txtDescription.getText().length() != 0
                    && txtQuantityBook.getText().length() != 0
                    && String.valueOf(cbbIdCate.getSelectedItem()).length() != 0
                    && String.valueOf(cbbIdPulisher.getSelectedItem()).length() != 0
                    && txtPriceBook.getText().length() != 0
                    && txtYearBook.getText().length() != 0
                    && txtNTimesBook.getText().length() != 0
                    && txtAuthorBook.getText().length() != 0) {
                if (Valid.ValidN(txtPriceBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtPriceBook.requestFocus();
                } else if (Valid.ValidYear(txtYearBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtYearBook.requestFocus();
                } else if (Valid.ValidN(txtNTimesBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtNTimesBook.requestFocus();
                } else if (Valid.ValidN(txtQuantityBook.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txtQuantityBook.requestFocus();
                } else if (bookDAO.Insert(new tblDocument(txtIdBook.getText(), txtNameBook.getText(), txtDescription.getText(), String.valueOf(cbbIdCate.getSelectedItem()), cbbIdPulisher.getSelectedItem().toString(),
                         Integer.parseInt(txtQuantityBook.getText()), txtPriceBook.getText(), txtYearBook.getText(),
                        Integer.parseInt(txtNTimesBook.getText()), txtAuthorBook.getText())) != null) {
                    JOptionPane.showMessageDialog(null, "Thêm tài liệu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    txtIdBook.setText("");
                    txtNameBook.setText("");
                    txtDescription.setText("");
                    cbbIdCate.setSelectedItem("");
                    cbbIdPulisher.setSelectedItem("");
                    txtQuantityBook.setText("");
                    txtPriceBook.setText("");
                    txtYearBook.setText("");
                    txtNTimesBook.setText("");
                    txtAuthorBook.setText("");

                    txtIdBook.requestFocus();

                    showTableBook(TableBookLib);

                } else {
                    JOptionPane.showMessageDialog(null, "Thêm tài liệu thất bại trùng mã tài liệu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Bạn không được để trống", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtIdBookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdBookFocusLost
        txtIdBook.setText(Valid.VToUpper(txtIdBook.getText()));
    }//GEN-LAST:event_txtIdBookFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBookLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DBookLib dialog = new DBookLib(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPa2;
    private javax.swing.JSeparator Sepa1;
    private javax.swing.JSeparator Sepa2;
    private javax.swing.JSeparator Sepa3;
    private javax.swing.JSeparator Sepa4;
    private javax.swing.JSeparator Sepa5;
    private javax.swing.JSeparator Sepa6;
    private javax.swing.JSeparator Sepa8;
    private javax.swing.JPanel btnSave;
    private javax.swing.JLabel btnX;
    private javax.swing.JComboBox<String> cbbIdCate;
    private javax.swing.JComboBox<String> cbbIdPulisher;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb13;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb9;
    private javax.swing.JPanel palD;
    private javax.swing.JTextField txtAuthorBook;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtIdBook;
    private javax.swing.JTextField txtNTimesBook;
    private javax.swing.JTextField txtNameBook;
    private javax.swing.JTextField txtPriceBook;
    private javax.swing.JTextField txtQuantityBook;
    private javax.swing.JTextField txtYearBook;
    // End of variables declaration//GEN-END:variables
}
