/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import BackgroundColor.SetBackgroundbtn;
import Controller.DateToDTime;
import Controller.Valid;
import Model.DataHelper;
import Model.MyDAO;
import Model.tblPayReader;
import Model.tblPayReaderDAO;
import Model.tblPayReaderModel;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import MoneyPay.*;

/**
 *
 * @author MacOS
 */
public class DReturnBook extends javax.swing.JDialog {

    static Point comPoint = null;
    MyDAO reDAO = new tblPayReaderDAO();
    public String id;
    public int number;
    public JTable TableReturn;
    private Connection conn;
    private PreparedStatement stmt;
    private ResultSet rs;

    public DReturnBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public DReturnBook(String id, String documentid, String readerid, String quantity, String datepay, String moneyborrow, String moneyreturn, String moneylost, int number, JTable tablereturn, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
        txtIdBook.setText(documentid);
        txtIdReader.setText(readerid);
        txtQuantityBook.setText(quantity);
        if (datepay.length() != 0) {
            txtDatePayBook.setDate(DateToDTime.SToDate(datepay));
        } else {
            txtDatePayBook.setDate(null);
        }
        txtMoneyBorrow.setText(moneyborrow);
        txtMoneyOutDate.setText(moneyreturn);
        txtMoneyLost.setText(moneylost);
        this.number = number;
        this.TableReturn = tablereturn;
        if (number == 1) {
            txtIdReader.setEditable(false);
            txtIdBook.requestFocus();
        } else {
            getDateNow();
        }
    }

    public void showTableReturn(JTable tablereturn) {
        tblPayReaderModel payReaderModel = new tblPayReaderModel();
        payReaderModel.setData(new tblPayReaderDAO().GetAll());
        tablereturn.setModel(payReaderModel);
    }

    private void getDateNow() {
        try {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date datenow = new Date();
            txtDatePayBook.setDate(dateFormat.parse(dateFormat.format(datenow)));
        } catch (ParseException ex) {
            Logger.getLogger(DReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CheckPubId() {
        try {
            conn = DataHelper.getConnection();
            String idreader = "";
            String sql = "select top 1* from tblBondReader where ReaderId=?";
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtIdReader.getText());
            rs = stmt.executeQuery();
            while (rs.next()) {
                idreader = rs.getString("ReaderId");

            }
            rs.close();
            conn.close();
            if (txtIdReader.getText().length() != 0) {
                if (!idreader.equals(txtIdReader.getText())) {
                    txtIdReader.requestFocus();
                    JOptionPane.showMessageDialog(null, "Độc giả này không mượn sách", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                }
            } else {
                txtIdReader.requestFocus();
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palD = new javax.swing.JPanel();
        btnX = new javax.swing.JLabel();
        btnPayBook = new javax.swing.JPanel();
        lb9 = new javax.swing.JLabel();
        btnLostBook = new javax.swing.JPanel();
        lb10 = new javax.swing.JLabel();
        btnTotalMoney = new javax.swing.JPanel();
        lb13 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        txtIdReader = new javax.swing.JTextField();
        Sepa1 = new javax.swing.JSeparator();
        txtIdBook = new javax.swing.JTextField();
        Sepa3 = new javax.swing.JSeparator();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        txtQuantityBook = new javax.swing.JTextField();
        Sepa5 = new javax.swing.JSeparator();
        lb3 = new javax.swing.JLabel();
        txtDatePayBook = new com.toedter.calendar.JDateChooser();
        lb7 = new javax.swing.JLabel();
        txtMoneyBorrow = new javax.swing.JTextField();
        Sepa6 = new javax.swing.JSeparator();
        txtMoneyOutDate = new javax.swing.JTextField();
        Sepa4 = new javax.swing.JSeparator();
        lb4 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        txtMoneyLost = new javax.swing.JTextField();
        Sepa7 = new javax.swing.JSeparator();
        Sepa8 = new javax.swing.JSeparator();
        lb12 = new javax.swing.JLabel();
        txtMoneyTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        palD.setBackground(new java.awt.Color(98, 98, 110));
        palD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                palDMouseDragged(evt);
            }
        });
        palD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                palDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                palDMouseReleased(evt);
            }
        });

        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
        });

        btnPayBook.setBackground(new java.awt.Color(126, 130, 139));
        btnPayBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayBookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPayBookMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPayBookMouseReleased(evt);
            }
        });

        lb9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb9.setForeground(new java.awt.Color(255, 255, 255));
        lb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb9.setText("Lưu Trả Sách");

        javax.swing.GroupLayout btnPayBookLayout = new javax.swing.GroupLayout(btnPayBook);
        btnPayBook.setLayout(btnPayBookLayout);
        btnPayBookLayout.setHorizontalGroup(
            btnPayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(btnPayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lb9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );
        btnPayBookLayout.setVerticalGroup(
            btnPayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(btnPayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lb9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        btnLostBook.setBackground(new java.awt.Color(126, 130, 139));
        btnLostBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLostBookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLostBookMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLostBookMouseReleased(evt);
            }
        });

        lb10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb10.setForeground(new java.awt.Color(255, 255, 255));
        lb10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb10.setText("Mất Sách");

        javax.swing.GroupLayout btnLostBookLayout = new javax.swing.GroupLayout(btnLostBook);
        btnLostBook.setLayout(btnLostBookLayout);
        btnLostBookLayout.setHorizontalGroup(
            btnLostBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb10, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        btnLostBookLayout.setVerticalGroup(
            btnLostBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        btnTotalMoney.setBackground(new java.awt.Color(126, 130, 139));
        btnTotalMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTotalMoneyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTotalMoneyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTotalMoneyMouseReleased(evt);
            }
        });

        lb13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb13.setForeground(new java.awt.Color(255, 255, 255));
        lb13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb13.setText("Thanh Toán");

        javax.swing.GroupLayout btnTotalMoneyLayout = new javax.swing.GroupLayout(btnTotalMoney);
        btnTotalMoney.setLayout(btnTotalMoneyLayout);
        btnTotalMoneyLayout.setHorizontalGroup(
            btnTotalMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb13, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnTotalMoneyLayout.setVerticalGroup(
            btnTotalMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb13, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        lb1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("Mã Độc Giả");

        txtIdReader.setBackground(new java.awt.Color(98, 98, 110));
        txtIdReader.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIdReader.setForeground(new java.awt.Color(255, 255, 255));
        txtIdReader.setBorder(null);
        txtIdReader.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdReader.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdReaderFocusLost(evt);
            }
        });

        txtIdBook.setBackground(new java.awt.Color(98, 98, 110));
        txtIdBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIdBook.setForeground(new java.awt.Color(255, 255, 255));
        txtIdBook.setBorder(null);
        txtIdBook.setCaretColor(new java.awt.Color(255, 255, 255));

        lb5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("Mã Sách");

        lb6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("Số Lượng");

        txtQuantityBook.setBackground(new java.awt.Color(98, 98, 110));
        txtQuantityBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQuantityBook.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantityBook.setBorder(null);
        txtQuantityBook.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQuantityBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityBookKeyReleased(evt);
            }
        });

        lb3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setText("Ngày Trả");

        txtDatePayBook.setDateFormatString("dd/MM/yyyy");
        txtDatePayBook.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lb7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb7.setForeground(new java.awt.Color(255, 255, 255));
        lb7.setText("Tiền Mượn ");

        txtMoneyBorrow.setEditable(false);
        txtMoneyBorrow.setBackground(new java.awt.Color(98, 98, 110));
        txtMoneyBorrow.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMoneyBorrow.setForeground(new java.awt.Color(255, 255, 255));
        txtMoneyBorrow.setBorder(null);
        txtMoneyBorrow.setCaretColor(new java.awt.Color(255, 255, 255));

        txtMoneyOutDate.setEditable(false);
        txtMoneyOutDate.setBackground(new java.awt.Color(98, 98, 110));
        txtMoneyOutDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMoneyOutDate.setForeground(new java.awt.Color(255, 255, 255));
        txtMoneyOutDate.setBorder(null);
        txtMoneyOutDate.setCaretColor(new java.awt.Color(255, 255, 255));

        lb4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("Tiền Phạt Quá Hạn");

        lb11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb11.setForeground(new java.awt.Color(255, 255, 255));
        lb11.setText("Tiền Phạt Mất ");

        txtMoneyLost.setEditable(false);
        txtMoneyLost.setBackground(new java.awt.Color(98, 98, 110));
        txtMoneyLost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMoneyLost.setForeground(new java.awt.Color(255, 255, 255));
        txtMoneyLost.setBorder(null);
        txtMoneyLost.setCaretColor(new java.awt.Color(255, 255, 255));

        lb12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb12.setForeground(new java.awt.Color(255, 255, 255));
        lb12.setText("Tổng Tiền");

        txtMoneyTotal.setEditable(false);
        txtMoneyTotal.setBackground(new java.awt.Color(98, 98, 110));
        txtMoneyTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMoneyTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtMoneyTotal.setBorder(null);
        txtMoneyTotal.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout palDLayout = new javax.swing.GroupLayout(palD);
        palD.setLayout(palDLayout);
        palDLayout.setHorizontalGroup(
            palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnX))
            .addGroup(palDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(palDLayout.createSequentialGroup()
                        .addComponent(btnPayBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnLostBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(palDLayout.createSequentialGroup()
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIdReader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb1)
                            .addComponent(lb5)
                            .addComponent(txtIdBook)
                            .addComponent(Sepa3)
                            .addComponent(lb6)
                            .addComponent(txtQuantityBook)
                            .addComponent(Sepa5)
                            .addComponent(lb3)
                            .addComponent(txtDatePayBook, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(palDLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoneyLost, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb11)
                                    .addComponent(Sepa7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoneyOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb4)
                                    .addComponent(Sepa4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoneyBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb7)
                                    .addComponent(Sepa6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(palDLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoneyTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb12)
                                    .addComponent(Sepa8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        palDLayout.setVerticalGroup(
            palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palDLayout.createSequentialGroup()
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(palDLayout.createSequentialGroup()
                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(palDLayout.createSequentialGroup()
                                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnX)
                                    .addGroup(palDLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(palDLayout.createSequentialGroup()
                                                .addComponent(lb1)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtIdReader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(Sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palDLayout.createSequentialGroup()
                                                .addComponent(lb7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMoneyBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(Sepa6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(palDLayout.createSequentialGroup()
                                .addComponent(lb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoneyOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Sepa4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(lb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatePayBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(palDLayout.createSequentialGroup()
                        .addComponent(lb11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoneyLost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Sepa7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(palDLayout.createSequentialGroup()
                        .addComponent(lb12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoneyTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Sepa8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(palDLayout.createSequentialGroup()
                        .addComponent(lb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantityBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Sepa5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(palDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPayBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLostBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMouseReleased
        comPoint = null;
    }//GEN-LAST:event_palDMouseReleased

    private void palDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMousePressed
        comPoint = evt.getPoint();
    }//GEN-LAST:event_palDMousePressed

    private void palDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palDMouseDragged
        Point cPoint = evt.getLocationOnScreen();
        this.setLocation(cPoint.x - comPoint.x, cPoint.y - comPoint.y);
    }//GEN-LAST:event_palDMouseDragged

    private void btnLostBookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLostBookMouseReleased
        new SetBackgroundbtn(btnLostBook).mouseReleased(evt);
    }//GEN-LAST:event_btnLostBookMouseReleased

    private void btnLostBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLostBookMousePressed
        new SetBackgroundbtn(btnLostBook).mousePressed(evt);
    }//GEN-LAST:event_btnLostBookMousePressed

    private void btnLostBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLostBookMouseClicked
        if (Valid.ValidN(txtQuantityBook.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            txtQuantityBook.requestFocus();
        } else if (txtIdReader.getText().length() != 0
                && txtIdBook.getText().length() != 0
                && txtQuantityBook.getText().length() != 0
                && txtDatePayBook.getDate() != null) {
            int mlost = new MoneyLost().TienMatSach(txtIdBook.getText(), Integer.parseInt(txtQuantityBook.getText()));
            txtMoneyLost.setText(String.valueOf(mlost));
            txtMoneyBorrow.setText("");
            txtMoneyOutDate.setText("");
        }

    }//GEN-LAST:event_btnLostBookMouseClicked

    private void btnPayBookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayBookMouseReleased
        new SetBackgroundbtn(btnPayBook).mouseReleased(evt);
    }//GEN-LAST:event_btnPayBookMouseReleased

    private void btnPayBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayBookMousePressed
        new SetBackgroundbtn(btnPayBook).mousePressed(evt);
    }//GEN-LAST:event_btnPayBookMousePressed

    private void btnPayBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayBookMouseClicked
        if (number == 1) {
            if (txtDatePayBook.getDate() != null
                    && txtIdBook.getText().length() != 0
                    && txtIdReader.getText().length() != 0
                    && txtQuantityBook.getText().length() != 0) {
                if (reDAO.Update(new tblPayReader(Integer.parseInt(id), txtIdBook.getText(), txtIdReader.getText(),
                        Integer.parseInt(txtQuantityBook.getText()), DateToDTime.Datechooser(txtDatePayBook), txtMoneyBorrow.getText(),
                        txtMoneyOutDate.getText(), txtMoneyLost.getText()
                )) != null) {
                    JOptionPane.showMessageDialog(null, "Sửa phiếu trả thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    showTableReturn(TableReturn);
                    this.dispose();

                }

            } else {
                JOptionPane.showMessageDialog(null, "Sửa phiếu trả thất bại bạn không được để trống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            if (txtDatePayBook.getDate() != null
                    && txtIdBook.getText().length() != 0
                    && txtIdReader.getText().length() != 0
                    && txtQuantityBook.getText().length() != 0) {
                if (reDAO.Insert(new tblPayReader(Integer.parseInt(id), txtIdBook.getText(), txtIdReader.getText(),
                        Integer.parseInt(txtQuantityBook.getText()), DateToDTime.Datechooser(txtDatePayBook), txtMoneyBorrow.getText(),
                        txtMoneyOutDate.getText(), txtMoneyLost.getText()
                )) != null) {
                    JOptionPane.showMessageDialog(null, "Thêm phiếu trả thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    txtIdBook.setText("");
                    txtMoneyBorrow.setText("");
                    txtMoneyLost.setText("");
                    txtMoneyOutDate.setText("");
                    //txtMoneyTotal.setText("");
                    txtQuantityBook.setText("");

                    txtIdBook.requestFocus();
                    showTableReturn(TableReturn);

                } else {
                    JOptionPane.showMessageDialog(null, "Thêm phiếu trả thất bại trùng mã tài liệu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Bạn không được để trống", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnPayBookMouseClicked

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        txtIdReader.setText("");
        this.dispose();
        showTableReturn(TableReturn);
    }//GEN-LAST:event_btnXMouseClicked

    private void txtIdReaderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdReaderFocusLost
        CheckPubId();
        txtIdReader.setText(Valid.VToUpper(txtIdReader.getText()));
    }//GEN-LAST:event_txtIdReaderFocusLost

    private void btnTotalMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMoneyMouseClicked
        if (txtIdReader.getText().length() != 0
                && txtDatePayBook.getDate() != null) {
            int mtotal = new TotalMoney().TongTienTra(DateToDTime.Datechooser(txtDatePayBook), txtIdReader.getText());
            txtMoneyTotal.setText(String.valueOf(mtotal));
        }
    }//GEN-LAST:event_btnTotalMoneyMouseClicked

    private void btnTotalMoneyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMoneyMousePressed
        new SetBackgroundbtn(btnTotalMoney).mousePressed(evt);
    }//GEN-LAST:event_btnTotalMoneyMousePressed

    private void btnTotalMoneyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMoneyMouseReleased
        new SetBackgroundbtn(btnTotalMoney).mouseReleased(evt);
    }//GEN-LAST:event_btnTotalMoneyMouseReleased

    private void txtQuantityBookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityBookKeyReleased
        if (Valid.ValidN(txtQuantityBook.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            txtQuantityBook.requestFocus();
        } else if (txtIdReader.getText().length() != 0
                && txtIdBook.getText().length() != 0
                && txtQuantityBook.getText().length() != 0
                && txtDatePayBook.getDate() != null) {
            int mborrow = new MoneyBorrow().TienMuon(txtIdBook.getText(), Integer.parseInt(txtQuantityBook.getText()));
            int moutdate = new MoneyReturn().TienQuaHan(DateToDTime.Datechooser(txtDatePayBook),
                    txtIdBook.getText(), txtIdReader.getText(), Integer.parseInt(txtQuantityBook.getText()));
            txtMoneyBorrow.setText(String.valueOf(mborrow));
            txtMoneyOutDate.setText(String.valueOf(moutdate));
        }

    }//GEN-LAST:event_txtQuantityBookKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DReturnBook dialog = new DReturnBook(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Sepa1;
    private javax.swing.JSeparator Sepa3;
    private javax.swing.JSeparator Sepa4;
    private javax.swing.JSeparator Sepa5;
    private javax.swing.JSeparator Sepa6;
    private javax.swing.JSeparator Sepa7;
    private javax.swing.JSeparator Sepa8;
    private javax.swing.JPanel btnLostBook;
    private javax.swing.JPanel btnPayBook;
    private javax.swing.JPanel btnTotalMoney;
    private javax.swing.JLabel btnX;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb13;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb9;
    private javax.swing.JPanel palD;
    private com.toedter.calendar.JDateChooser txtDatePayBook;
    private javax.swing.JTextField txtIdBook;
    private javax.swing.JTextField txtIdReader;
    private javax.swing.JTextField txtMoneyBorrow;
    private javax.swing.JTextField txtMoneyLost;
    private javax.swing.JTextField txtMoneyOutDate;
    private javax.swing.JTextField txtMoneyTotal;
    private javax.swing.JTextField txtQuantityBook;
    // End of variables declaration//GEN-END:variables
}
